###
GET http://localhost:3000/api/comments


###
GET http://localhost:3000/api/comments/1

###
POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "description" : "desc1",
    "author": "author1",
    "email": "Barack@whitehouse.gov"
}


###
GET http://localhost:3000/api/posts

###
DELETE  http://localhost:3000/api/comments/1


###
PATCH  http://localhost:3000/api/comments/1
Content-Type: application/json

{
    "description" : "desc11",
    "author": "author11",
    "email": "Barack11@whitehouse.gov",
    "id": 1
}